[tool.poetry]
name = "task"
version = "0.1.0"
description = ""
authors = ["klukashka <klukin0202@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
